title: XenonKnight
description: Moving Forward Game Developer
baseurl: /XenonKnight
repository: XenonKnight33.github.io
remote_theme: YoussefRaafatNasry/portfolYOU
plugins:
  - jemoji
nav_exclude:
  - pages/tags.html
  - pages/404.html
  - pages/index.md
author:
  name: Xenon Knight
  image: WhatsApp Image 2020-07-05 at 16.11.31.jpeg
  behance: your_username
  email: Kekkaishi@Ymail.com
  facebook: your_username
  github: your_username
  linkedin: your_username
  medium: your_username
  twitter: your_username
permalink: '/blog/:title'
collections:
  projects:
    output: true
    permalink: '/projects/:name'
disqus: your-short-name-disqus
analytics:
  enabled: false
  google:
    tracking_id: your-google-tracking-id
defaults:
  - scope:
      path: ''
      type: projects
    values:
      layout: page
  - scope:
      path: ''
      type: posts
    values:
      comments: false
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - '*.log'
